// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransBrain.Infrastructure.Persistence;

#nullable disable

namespace TransBrain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransBrainDbContext))]
    [Migration("20260829130200_AddTours")]
    partial class AddTours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransBrain.Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("C");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("C");

                    b.Property<string>("LicenseClassesRaw")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_classes");

                    b.Property<DateOnly>("LicenseValidUntil")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasFilter("\"ExternalUserId\" IS NOT NULL");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("TransBrain.Domain.Orders.TransportOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("order_number")
                        .UseCollation("C");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("transport_orders", (string)null);
                });

            modelBuilder.Entity("TransBrain.Domain.Tours.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("TourDate")
                        .HasColumnType("date")
                        .HasColumnName("tour_date");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("TourDate", "DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_tours_date_driver_unique");

                    b.HasIndex("TourDate", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_tours_date_vehicle_unique");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("TransBrain.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .UseCollation("C");

                    b.Property<decimal>("LoadMeters")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly>("NextInspectionDue")
                        .HasColumnType("date");

                    b.Property<int>("PayloadKg")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("TransBrain.Domain.Orders.TransportOrder", b =>
                {
                    b.OwnsOne("TransBrain.Domain.Common.Cargo", "Cargo", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("cargo_description");

                            b1.Property<decimal>("LoadMeters")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("cargo_load_meters");

                            b1.Property<int>("WeightKg")
                                .HasColumnType("integer")
                                .HasColumnName("cargo_weight_kg");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("transport_orders");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("TransBrain.Domain.Common.Address", "Consignee", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignee_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("consignee_country");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignee_name");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("consignee_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignee_street");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("transport_orders");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("TransBrain.Domain.Common.Address", "Consignor", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignor_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("consignor_country");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignor_name");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("consignor_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("consignor_street");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("transport_orders");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("TransBrain.Domain.Common.TimeWindow", "DeliveryWindow", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_from");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivery_to");

                            b1.HasKey("TransportOrderId");

                            b1.ToTable("transport_orders");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.OwnsOne("TransBrain.Domain.Common.TimeWindow", "PickupWindow", b1 =>
                        {
                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("pickup_from");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("pickup_to");

                            b1.HasKey("TransportOrderId");

                            b1.HasIndex("From");

                            b1.ToTable("transport_orders");

                            b1.WithOwner()
                                .HasForeignKey("TransportOrderId");
                        });

                    b.Navigation("Cargo")
                        .IsRequired();

                    b.Navigation("Consignee")
                        .IsRequired();

                    b.Navigation("Consignor")
                        .IsRequired();

                    b.Navigation("DeliveryWindow")
                        .IsRequired();

                    b.Navigation("PickupWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("TransBrain.Domain.Tours.Tour", b =>
                {
                    b.OwnsMany("TransBrain.Domain.Tours.TourStop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("tour_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("StopType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("stop_type");

                            b1.Property<Guid>("TransportOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("transport_order_id");

                            b1.HasKey("tour_id", "Id");

                            b1.ToTable("tour_stops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("tour_id");
                        });

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
